apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-repo
  labels:
    app: app-repo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-repo
  template:
    metadata:
      labels:
        app: app-repo
    spec:
      containers:
      - name: app-repo
        image: kiruthigaa05/app-repo:decc3fb3afc06d8f7749844e726c6d17ce4c0da2
        ports:
        - containerPort: 80